### ISSUE TITLE
error of babel/register and require stack

### ISSUE THREAD

**Issue by MThakkar121** [dappuniversity/defi_tutorial#1]
![mintty_Djv0r2wg1J](https://user-images.githubusercontent.com/36958377/92313556-bc5fc480-efea-11ea-8044-c091c4511657.png)

help me to resolve this, what am i lacking of in here ?

**Comment by jayweezy247** [comment]
This resolved that particular issue for me:

`cd defi_tutorial`
THEN
`npm install @babel/core @babel/register --save-dev`

Resource:
[https://stackoverflow.com/questions/53748871/error-cannot-find-module-babel-register](url)

**Comment by MThakkar121** [comment]
perfect solved my error, THANK YOU!
