### ISSUE TITLE
Truffle Migrates only first file from the "Migration" Folder

### ISSUE THREAD

**Issue by Akhil1232** [dappuniversity/defi_tutorial#4]
![MIgration issue](https://user-images.githubusercontent.com/66204243/109396562-3f3d5880-7958-11eb-81a4-bc9d01a6e395.PNG)

I tried using (-f x --to -x) but still not able to migrate the files except for the 1_initial_migration.js . Please help.

**Comment by one-n-dunn** [comment]
Same thing is happening to me. I was wondering if you were able to resolve this?

**Comment by Akhil1232** [comment]
> ?

No I couldn't but i tried the same thing in Linux and it worked, So most probably its an issue with windows,yet Not so Sure.

**Comment by one-n-dunn** [comment]
I think you're right about Windows, their were a lot more hoops to jump through just working on the beginning phases of the tutorial. He had posted another vid a lil while ago talking about his work setup. He made an argument for using Mac OS and Linux over Windows basically stating that they were better suited  for immediate use. I went over to my Mac laptop and it worked out just fine as well 👍🏻
